# Site settings
title: CreaDev's blog
email: info@creadev.co
description: CreaDev es una empresa eficiente, innovadora y creativa en busca cada día de la excelencia. Creadev desarrolla, diseña e innova en desarrollo de páginas web, diseño gráfico y producción de fotografía y video. Creadev busca ofrecerle a cada cliente un producto de acuerdo a su necesidad.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
twitter_username: creadev_co
github_username:  creadevco

# Build settings
markdown: kramdown

paginate: 4

author: CreaDev

gems: [jekyll-paginate]
